// Curated list of major U.S. health-insurance payers and common plan brands.
// Not exhaustive — the provider field accepts free text for anything not listed.
// Iowa-relevant plans (Wellmark, Iowa Total Care, Amerigroup Iowa) are included
// alongside national carriers since this site serves the Des Moines area.
export const INSURANCE_PROVIDERS = [
  'Aetna',
  'Amerigroup',
  'Amerigroup Iowa',
  'Ambetter',
  'Anthem Blue Cross Blue Shield',
  'Beacon Health Options',
  'Blue Cross Blue Shield',
  'Carelon Behavioral Health',
  'CareSource',
  'Centene',
  'Cigna',
  'ComPsych',
  'Elevance Health',
  'Empire Blue Cross Blue Shield',
  'First Health',
  'GEHA',
  'Health Net',
  'Highmark',
  'Humana',
  'Iowa Total Care',
  'Kaiser Permanente',
  'Magellan Health',
  'Medica',
  'Medicaid',
  'Medicare',
  'Meritain Health',
  'Molina Healthcare',
  'MultiPlan',
  'Optum',
  'Oscar Health',
  'Oxford Health Plans',
  'PHCS',
  'Premera Blue Cross',
  'TRICARE',
  'UMR',
  'UnitedHealthcare',
  'Wellmark Blue Cross Blue Shield',
  'WellCare',
]
